name: ${project.artifactId}
description: ${project.description}
main: ${project.groupId}.${project.artifactId}.${project.artifactId}
version: ${project.version}
author: MiaoWoo
website: ${ciManagement.url}
load: STARTUP
softdepend:
- PlaceholderAPI
- Vault
